schema: pdl-api-schema.graphql
extensions:
  endpoints:
    PDL GraphQL Endpoint:
      url: https://pdl-api.dev.adeo.no/graphql
      headers:
        user-agent: familie-integrasjoner
      introspect: false
