apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-integrasjoner
  namespace: default
  labels:
    team: teamfamilie

spec:
  image: docker.pkg.github.com/navikt/familie/familie-integrasjoner:{{tag}}
  port: 8085
  liveness:
    path: /internal/health
    initialDelay: 30
    timeout: 5
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 30
    timeout: 5
    failureThreshold: 10
  vault:
    enabled: true
  secureLogs:
    enabled: true
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 2Gi
      cpu: 1500m
    requests:
      memory: 1Gi
      cpu: 200m
  ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
    - https://familie-integrasjoners.nais.adeo.no
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
