apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-integrasjoner
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  port: 8085
  liveness:
    path: /internal/status/isAlive
    initialDelay: 30
    timeout: 5
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 30
    timeout: 5
    failureThreshold: 10
  vault:
    enabled: true
  secureLogs:
    enabled: true
  prometheus:
    enabled: true
    path: /internal/prometheus
  azure:
    application:
      enabled: true
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 2Gi
      cpu: 1500m
    requests:
      memory: 1Gi
      cpu: 200m
  ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
    - https://familie-integrasjoner.prod-fss-pub.nais.io
    - https://familie-integrasjoner.nais.adeo.no
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
