apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-integrasjoner
  namespace: teamfamilie
  labels:
    team: teamfamilie
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "250M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"

spec:
  image: {{ image }}
  port: 8085
  envFrom:
    - secret: familie-integrasjoner-sftp
  liveness:
    path: /internal/status/isAlive
    initialDelay: 30
    timeout: 5
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 30
    timeout: 5
    failureThreshold: 10
  vault:
    enabled: true
  webproxy: true
  azure:
    application:
      tenant: "trygdeetaten.no"
      enabled: true
      claims:
        groups:
          - id: "dbe4ad45-320b-4e9a-aaa1-73cca4ee124d"  # 0000-GA-Egne_ansatte
          - id: "ea930b6b-9397-44d9-b9e6-f4cf527a632a"  # 0000-GA-Fortrolig_Adresse
          - id: "5ef775f2-61f8-4283-bf3d-8d03f428aa14"  # 0000-GA-Strengt_Fortrolig_Adresse
          - id: "93a26831-9866-4410-927b-74ff51a9107c"  # 0000-GA-Barnetrygd-Veileder
          - id: "d21e00a4-969d-4b28-8782-dc818abfae65"  # 0000-GA-Barnetrygd
          - id: "9449c153-5a1e-44a7-84c6-7cc7a8867233"  # 0000-GA-Barnetrygd-Beslutter
          - id: "01166863-22f1-4e16-9785-d7a05a22df74"  # 0000-GA-Enslig-Forsorger-Beslutter
          - id: "ee5e0b5e-454c-4612-b931-1fe363df7c2c"  # 0000-GA-Enslig-Forsorger-Saksbehandler
          - id: "19dcbfde-4cdb-4c64-a1ea-ac9802b03339"  # 0000-GA-Enslig-Forsorger-Veileder
        extra:
          - "NAVident"
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: familie-ks-sak
          cluster: dev-gcp
        - application: familie-ks-sak
          cluster: dev-fss
        - application: familie-ba-sak
          cluster: dev-gcp
        - application: familie-ba-minside-frontend
          cluster: dev-gcp
        - application: familie-tilbake
          cluster: dev-gcp
        - application: familie-tilbake-lokal
          cluster: dev-gcp
        - application: tilbakekreving-backend
          namespace: tilbake
          cluster: dev-gcp
        - application: familie-ks-mottak
        - application: familie-baks-mottak
          cluster: dev-gcp
        - application: familie-ef-mottak
        - application: familie-ef-mottak
          cluster: dev-gcp
        - application: familie-klage
          cluster: dev-gcp
        - application: familie-klage-lokal
          cluster: dev-gcp
        - application: familie-ef-sak
          cluster: dev-gcp
        - application: familie-ef-sak-lokal
          cluster: dev-gcp
        - application: familie-ef-iverksett
          cluster: dev-gcp
        - application: familie-ef-iverksett-lokal
          cluster: dev-gcp
        - application: familie-ef-personhendelse
          cluster: dev-gcp
        - application: familie-ef-proxy
        - application: azure-token-generator
          namespace: nais
          cluster: dev-gcp
        - application: tokenx-token-generator
          namespace: nais
          cluster: dev-gcp
        - application: gjenlevende-bs-sak
          namespace: etterlatte
          cluster: dev-gcp
    outbound:
      rules:
        - application: modiacontextholder
          namespace: personoversikt
          cluster: dev-gcp
        - application: logging
          namespace: nais-system
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      memory: 2Gi
    requests:
      memory: 1Gi
      cpu: 200m
  ingresses:
    - https://familie-integrasjoner.dev-fss-pub.nais.io
    - https://familie-integrasjoner.intern.dev.nav.no

  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: preprod
