no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
    accepted_audience: ${AZURE_APP_CLIENT_ID}
    proxyurl: http://webproxy-nais.nav.no:8088
    cookie_name: azure_token
  client:
    registration:
      aad-graph-onbehalfof:
        resource-url: ${AAD_GRAPH_API_URI}
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: ${AAD_GRAPH_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      aad-graph:
        resource-url: ${AAD_GRAPH_API_URI}
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: ${AAD_GRAPH_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      dokarkiv-onbehalf-of:
        resource-url: ${DOKARKIV_V1_URL}
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: ${DOKARKIV_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      saf-onbehalf-of:
        resource-url: ${SAF_URL}
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: ${SAF_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      saf:
        resource-url: ${SAF_URL}
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: ${SAF_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      oppgave-onbehalf-of:
        resource-url: ${OPPGAVE_URL}
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: ${OPPGAVE_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      oppgave:
        resource-url: ${OPPGAVE_URL}
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: ${OPPGAVE_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      infotrygd:
        resource-url: ${INFOTRYGD_URL}
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: ${INFOTRYGD_KS_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      medl2:
        resource-url: ${MEDL2_URL}
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: api://dev-fss.team-rocket.medlemskap-medl-api-q1/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      pdl:
        resource-url: ${PDL_URL}
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: ${PDL_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      pdl-onbehalf-of:
        resource-url: ${PDL_URL}
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: ${PDL_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic

DOKARKIV_SCOPE: api://dev-fss.teamdokumenthandtering.dokarkiv-q1/.default
PDL_SCOPE: api://dev-fss.pdl.pdl-api-q1/.default

AAD_GRAPH_API_URI: https://graph.microsoft.com/v1.0/
ORGANISASJON_URL: https://ereg-services-q1.dev.intern.nav.no
DOKARKIV_V1_URL: https://dokarkiv-q1.dev.intern.nav.no
MEDL2_URL: https://medlemskap-medl-api-q1.dev.intern.nav.no
SAF_URL: https://saf-q1.dev.intern.nav.no
OPPGAVE_URL: http://oppgave-q1.oppgavehandtering
FORSTESIDEGENERATOR_URL: https://foerstesidegenerator-q1.dev.intern.nav.no
EGEN_ANSATT_URL: https://skjermede-personer-pip.nais.preprod.local
DOKDIST_URL: https://dokdistfordeling-q1.dev.intern.nav.no
AAREG_URL: https://aareg-services-q1.dev.intern.nav.no/api
SKYGGE_SAK_URL: https://sak-q1.dev.intern.nav.no
NORG2_URL: https://norg2.dev.adeo.no/norg2/

PDL_URL: http://pdl-api-q1.pdl
SFTP_HOST: b27apvl00364.preprod.local
