tilgang:
  kode6:
    rolle-id: "a1b518e2-3947-478d-8929-e5d685c47cac"
  kode7:
    rolle-id: "2e1dc582-f762-4510-a660-88bf68fb7128"
  egenAnsatt:
    rolle-id: "dbe4ad45-320b-4e9a-aaa1-73cca4ee124d"

NAIS_TOKEN_ENDPOINT: http://localhost/token
NAIS_TOKEN_EXCHANGE_ENDPOINT: http://localhost/token/exchange

SFTP_HOST: localhost
SFTP_PORT: 18321
SFTP_PRIVATE_KEY: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tClByb2MtVHlwZTogNCxFTkNSWVBURUQKREVLLUluZm86IEFFUy0xMjgtQ0JDLDdEMThBQTYwQjJEOTlERTc3RTE2NDU3NDNEOUI2M0Q1CgozeDdyNno0WXdxUWl0Tk5iTzE3b1ExQmsrSEQyR0hQRUwrY1Y1ZDc4YlhYeDJ6ekIxZm8zRG5sdjJWNVI2cTVWClZJcVJxNkV0d2p1YUwybEs5ZW50NGszSS9YRTh4Q3RIL1d0LzE3b3dqZ1pkbDZHZFJCODNCN3FuakN1UEpEVjQKZ2RxMmJzUWF5NzEzd1FEeVI0bnd4R3NmMmxYbUlBOFBlNFFJVTVGM1h0UXIrRm1rL1Jtb0pGbDFONlRCTGdRbwo2WDBCQjNUMUw5Q2dadGQ4Y0VydVViK1hlQUhzTlI2VG1OL3hxaVMzUHdVdWdRdzhzRUd1azI2QWRPMjZjZGs5Cm1xd3lCUWZ3UDdPajhMR3U5NjduRWdCZXVsY25YQ1I4UDR5WVg5L201MFU9Ci0tLS0tRU5EIEVDIFBSSVZBVEUgS0VZLS0tLS0K
SFTP_PASSPHRASE: Palpatine

AAD_GRAPH_API_URI: http://localhost:28085
ORGANISASJON_URL: #Denne er ikke i bruk da OrganisasjonV5 mockes ut lokalt
DOKARKIV_V1_URL: http://localhost:28085
DOKDIST_URL: http://localhost:28085
DOKDISTKANAL_URL: http://localhost:28085
EGEN_ANSATT_URL: #Mockes ut lokalt
KODEVERK_URL: http://kodeverk.team-rocket
FORSTESIDEGENERATOR_URL: http://localhost:28085
AAREG_URL: http://localhost:28085
SKYGGE_SAK_URL: #Mocker lokalt
NORG2_URL: #Mockes lokalt
MODIA_CONTEXT_HOLDER_URL: #Mockes lokalt
ARBEID_INNTEKT_URL: #Mockes lokalt
SAF_SELVBETJENING_URL:

SAF_URL: http://localhost:28085/rest/saf
OPPGAVE_URL: http://localhost:28085
PDL_URL: http://localhost:28085/rest/pdl
REGOPPSLAG_URL: http://localhost:28085
CREDENTIAL_USERNAME: not-a-real-srvuser
CREDENTIAL_PASSWORD: not-a-real-pw

wiremock:
  reset-mappings-after-each-test: true

NAIS_APP_NAME: familie-integrasjoner

AZURE_OPENID_CONFIG_TOKEN_ENDPOINT: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/v2.0/token