no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: https://login.microsoftonline.com/navq.onmicrosoft.com/v2.0/.well-known/openid-configuration
    accepted_audience: ${INTEGRASJONER_CLIENT_ID}
    cookie_name: azure_token
  client:
    registration:
      aad-graph-onbehalfof:
        resource-url: ${AAD_GRAPH_API_URI}
        token-endpoint-url: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/v2.0/token
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: ${INTEGRASJONER_AAD_GRAPH_SCOPE}
        authentication:
          client-id: ${INTEGRASJONER_CLIENT_ID}
          client-secret: ${INTEGRASJONER_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      infotrygd:
        resource-url: ${INFOTRYGD_URL}
        token-endpoint-url: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/v2.0/token
        grant-type: client_credentials
        scope: ${INTEGRASJONER_INFOTRYGD_KS_SCOPE}
        authentication:
          client-id: ${INTEGRASJONER_CLIENT_ID}
          client-secret: ${INTEGRASJONER_CLIENT_SECRET}
          client-auth-method: client_secret_basic

AAD_URL: http://vtp:8060/rest/isso/oauth2/access_token

AAD_GRAPH_API_URI: https://graph.microsoft.com/v1.0/
STS_URL: http://nav-auth-mock:8200/nais-sts/token
SECURITYTOKENSERVICE_URL: http://vtp:8060/soap/SecurityTokenServiceProvider/
PERSON_V3_URL: https://vtp:8063/soap/tpsws/ws/Person/v3
DOKARKIV_V1_URL: http://vtp:8060/rest/dokarkiv/rest/journalpostapi/v1
DOKDIST_URL: http://nowhere
KODEVERK_URL: http://nowhere
INFOTRYGD_URL: http://vtp:8060/rest/infotrygd-kontantstotte
EGEN_ANSATT_V1_URL: https://vtp:8063/soap/tpsws/EgenAnsatt_v1
MEDL2_URL: http://vtp:8060/rest/medl2
SAF_URL: http://vtp:8060/rest/api/saf
OPPGAVE_URL: http://vtp:8060/rest/dokarkiv/rest/oppgave-kontantstotte
ARBEIDSFORDELING_V1_URL: http://vtp:8060/soap/norg2/ws/Arbeidsfordeling/v1

PDL_URL: http://familie-mock-server:1337/rest/api/pdl
AKTOERID_URL: http://familie-mock-server:1337/rest/aktoerregister

CREDENTIAL_USERNAME: not-a-real-srvuser
CREDENTIAL_PASSWORD: not-a-real-pw

logging:
  config: "classpath:logback-e2e.xml"