no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: http://vtp:8060/rest/isso/oauth2/.well-known/openid-configuration
    accepted_audience: OIDC
    cookie_name: localhost-idtoken
  client:
    registration:
      aad-graph-onbehalfof:
        resource-url: https://login.microsoftonline.com
        token-endpoint-url: http://vtp:8060/rest/isso/oauth2/access_token
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: ${AAD_GRAPH_SCOPE}
        authentication:
          client-id: ${INTEGRASJONER_CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          client-auth-method: client_secret_basic

AAD_URL: http://vtp:8060/rest/isso/oauth2/access_token
INTEGRASJONER_CLIENT_ID: ""
CLIENT_SECRET: ""
INFOTRYGD_KS_SCOPE: ""

AAD_GRAPH_API_URI: https://graph.microsoft.com/v1.0/
SECURITYTOKENSERVICE_URL: http://vtp:8060/soap/SecurityTokenServiceProvider/
AKTOERID_URL: #TODO lokal mockserver AKTOERID_URL
PERSON_V3_URL: #TODO lokal mockserver PERSON_V3_URL
DOKARKIV_V1_URL: #TODO lokal mockserver DOKARKIV_V1_URL
INFOTRYGD_URL: http://vtp:8060/rest/infotrygd-kontantstotte
INNSYN_JOURNAL_V2_URL: #TODO lokal mockserver INNSYN_JOURNAL_V2_URL
EGEN_ANSATT_V1_URL: #TODO lokal mockserver EGEN_ANSATT_V1_URL

MEDL2_URL: #TODO lokal mockserver MEDL2_URL
SAF_URL: #TODO lokal mockserver SAF_URL
OPPGAVE_URL: #TODO lokal mockserver OPPGAVE_URL
CREDENTIAL_USERNAME: not-a-real-srvuser
CREDENTIAL_PASSWORD: not-a-real-pw