no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: http://vtp:8060/rest/isso/oauth2/.well-known/openid-configuration
    accepted_audience: OIDC
    cookie_name: localhost-idtoken
  client:
    registration:
      aad-graph-onbehalfof:
        resource-url: https://login.microsoftonline.com
        token-endpoint-url: http://vtp:8060/rest/isso/oauth2/access_token
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: ${AAD_GRAPH_SCOPE}
        authentication:
          client-id: ${INTEGRASJONER_CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
          client-auth-method: client_secret_basic

AAD_URL: http://vtp:8060/rest/isso/oauth2/access_token
INTEGRASJONER_CLIENT_ID: ""
CLIENT_SECRET: ""
INFOTRYGD_KS_SCOPE: ""

AAD_GRAPH_API_URI: https://graph.microsoft.com/v1.0/
SECURITYTOKENSERVICE_URL: http://vtp:8060/soap/SecurityTokenServiceProvider/
AKTOERID_URL: http://vtp:8060/rest/aktoerregister
PERSON_V3_URL: http://vtp:8060/soap/tpsws/ws/Person/v3
DOKARKIV_V1_URL: http://vtp:8060/rest/dokarkiv/rest/journalpostapi/v1
INFOTRYGD_URL: http://vtp:8060/rest/infotrygd-kontantstotte
INNSYN_JOURNAL_V2_URL: http://vtp:8060/soap/joark/InnsynJournal/v2
EGEN_ANSATT_V1_URL: http://vtp:8060/soap/tpsws/EgenAnsatt_v1
MEDL2_URL: http://vtp:8060/rest/medl2
SAF_URL: http://vtp:8060/rest/api/saf
OPPGAVE_URL: http://vtp:8060/rest/dokarkiv/rest/oppgave-kontantstotte

CREDENTIAL_USERNAME: not-a-real-srvuser
CREDENTIAL_PASSWORD: not-a-real-pw