schema: saf-schema.graphql
# Kallet virker ikke, men får hjelp med valideringen i intellij
# https://github.com/navikt/saf/blob/master/app/src/main/resources/schemas/saf.graphqls
extensions:
  endpoints:
    SAF GraphQL Endpoint:
      url: https://saf-q2.dev.intern.nav.no/graphql
      headers:
        user-agent: ''
      introspect: false
