name: 'Remove Old Images'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:
  remove-images:
    name: 'Remove old images job'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'familie-integrasjoner/familie-integrasjoner'
          package-type: 'container'
          min-versions-to-keep: 1
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'familie-integrasjoner'
          package-type: 'container'
          min-versions-to-keep: 1
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'familie-integrasjoner-q1'
          package-type: 'container'
          min-versions-to-keep: 1
          token: ${{ secrets.PAT }}
