name: Build-Deploy-Preprod-Q1
on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

concurrency: q1
env:
  IMAGE: ghcr.io/navikt/familie-integrasjoner-q1:${{ github.sha }}
jobs:
  deploy-to-dev:
    if: github.event.pull_request.draft == false
    name: Build, push and deploy to dev-fss Q1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
      - name: Bygg med maven
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B -D skipTests --no-transfer-progress package --settings .m2/maven-settings.xml --file pom.xml
      - name: Bygg Docker image
        run: |
          docker build -t $IMAGE .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        run: docker push $IMAGE
      - name: Deploy til dev-fss team namespace q1
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: app-preprod.teamfamilie.q1.yaml
