name: run-e2e-ba-sak
on:
  workflow_dispatch:
env:
  IMAGE: ghcr.io/navikt/familie-integrasjoner:${{ github.sha }}
  IMAGE_UTEN_TAG: ghcr.io/navikt/familie-integrasjoner
jobs:
  run-e2e:
    name: Run e2e
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - uses: actions/cache@v2.1.6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-cache-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-cache-
      - name: Bygg med maven + sonar
        env:
          SONAR_PROJECTKEY: ${{ secrets.SONAR_PROJECTKEY }}
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B --no-transfer-progress package verify sonar:sonar --settings .m2/maven-settings.xml --file pom.xml
      - name: Bygg Docker image
        run: |
          docker build -t ${IMAGE} -t ${IMAGE_UTEN_TAG}:latest .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@ab80d026d4753220c4243394c07c7d80f9638d06
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        run: docker push $IMAGE
      - uses: navikt/github-app-token-generator@v1.1
        id: get-token
        with:
          private-key: ${{ secrets.REPO_CLONER_PRIVATE_KEY }}
          app-id: ${{ secrets.REPO_CLONER_APP_ID }}
      - name: Checkout e2e tests
        uses: actions/checkout@v2.3.4
        with:
          repository: navikt/familie-ba-e2e
          token: ${{ steps.get-token.outputs.token }}
          path: ba-e2e
      - name: Setter riktig integrasjoner-versjon i e2e tester
        run: sed -i 's/familie-integrasjoner:latest/familie-integrasjoner:'$GITHUB_SHA'/g' ba-e2e/e2e/docker-compose.yml
      - name: Start alle apper (e2e)
        env:
          MOTTAK_CLIENT_ID: ${{ secrets.MOTTAK_CLIENT_ID }}
          MOTTAK_FRONTEND_CLIENT_ID: ${{ secrets.MOTTAK_FRONTEND_CLIENT_ID }}
          MOTTAK_CLIENT_SECRET: ${{ secrets.MOTTAK_CLIENT_SECRET }}
          MOTTAK_BA_SAK_SCOPE: ${{ secrets.MOTTAK_BA_SAK_SCOPE }}
          MOTTAK_FAMILIE_INTEGRASJONER_SCOPE: ${{ secrets.MOTTAK_FAMILIE_INTEGRASJONER_SCOPE }}
          INTEGRASJONER_CLIENT_ID: ${{ secrets.INTEGRASJONER_CLIENT_ID }}
          INTEGRASJONER_CLIENT_SECRET: ${{ secrets.INTEGRASJONER_CLIENT_SECRET }}
          INTEGRASJONER_INFOTRYGD_KS_SCOPE: ${{ secrets.INTEGRASJONER_INFOTRYGD_KS_SCOPE }}
          INTEGRASJONER_AAD_GRAPH_SCOPE: ${{ secrets.INTEGRASJONER_AAD_GRAPH_SCOPE }}
          SAK_CLIENT_ID: ${{ secrets.SAK_CLIENT_ID }}
          SAK_FRONTEND_CLIENT_ID: ${{ secrets.SAK_FRONTEND_CLIENT_ID }}
          SAK_CLIENT_SECRET: ${{ secrets.SAK_CLIENT_SECRET}}
          INTEGRASJONER_SCOPE: ${{ secrets.INTEGRASJONER_SCOPE }}
          OPPDRAG_SCOPE: ${{ secrets.OPPDRAG_SCOPE }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          SAK_FRONTEND_CLIENT_SECRET: ${{ secrets.SAK_FRONTEND_CLIENT_SECRET }}
          BA_SAK_SCOPE: ${{ secrets.BA_SAK_SCOPE }}
          OPPDRAG_CLIENT_ID: ${{ secrets.OPPDRAG_CLIENT_ID }}
          SRVUSER_BA_SAK_SECRET: ${{ secrets.SRVUSER_BA_SAK_SECRET }}
        run: cd ba-e2e/e2e; ./e2e.sh
      - name: Kjør tester (e2e)
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cd ba-e2e/autotest; mvn --settings .m2/maven-settings.xml -Dtest="**" test
      - name: Samle Docker-logs ved feil
        if: failure()
        uses: jwalton/gh-docker-logs@v2
        with:
          dest: './logs'
      - name: Tar logs
        if: failure()
        run: tar cvzf ./logs.tgz ./logs
      - name: Laste opp logs til GitHub
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: docker-logs-${{ github.run_number }}.tgz
          path: ./logs.tgz
          retention-days: 2