name: Main
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.github/**.yaml'
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: "read"
  id-token: "write"

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # ratchet:actions/setup-java@v4
        with:
          java-version: 25
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B --no-transfer-progress package --settings .m2/maven-settings.xml --file pom.xml

      - name: Build and push docker image
        uses: nais/docker-build-push@be85229e81c0293c265c646c084f05317fb6e0d2 # ratchet:nais/docker-build-push@v0
        id: docker-push
        with:
          team: teamfamilie
          tag: latest
          byosbom: target/classes/META-INF/sbom/application.cdx.json

    outputs:
      image: ${{ steps.docker-push.outputs.image }}

  deploy-dev:
    name: Deploy to dev-fss
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v4

      - name: Deploy to dev-fss namespace
        uses: nais/deploy/actions/deploy@823ec9b7e305ce7cf911d0f9a25f7da9d7486cf2 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-fss
          RESOURCE: .nais/app-dev.yaml
          VAR: image=${{ needs.build.outputs.image }}

  deploy-prod:
    name: Deploy to prod-fss
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v4

      - name: Deploy to prod-fss namespace
        uses: nais/deploy/actions/deploy@823ec9b7e305ce7cf911d0f9a25f7da9d7486cf2 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-fss
          RESOURCE: .nais/app-prod.yaml
          VAR: image=${{ needs.build.outputs.image }}

  loggfeil:
    name: Send log to Slack on failure
    runs-on: ubuntu-latest
    needs: [deploy-prod]
    if: failure()
    steps:
      - name: Send log to Slack on failure
        run: |
          curl -X POST --data "{\"text\": \"Deploy of $GITHUB_REPOSITORY failed - $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\"}" $WEBHOOK_URL
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
